/Users/uuboy.scy/PycharmProjects/pyetl_eb101/venv/bin/python "/Applications/PyCharm CE.app/Contents/helpers/pydev/pydevd.py" --multiproc --qt-support=auto --client 127.0.0.1 --port 51534 --file /Users/uuboy.scy/PycharmProjects/pyetl_eb101/json_dcard_practice.py
pydev debugger: process 82383 is connecting

Connected to pydev debugger (build 192.6603.34)
id
title
excerpt
anonymousSchool
anonymousDepartment
pinned
forumId
replyId
createdAt
updatedAt
commentCount
likeCount
withNickname
tags
topics
meta
forumName
forumAlias
gender
school
department
replyTitle
reportReason
mediaMeta
reactions
hidden
customStyle
isSuspiciousAccount
layout
withImages
withVideos
media
reportReasonText
postAvatar

Process finished with exit code 0
